### PR TITLE
Translate all code into C++

### PR DESCRIPTION
**Pull request by tsandstr**

### CODE REVIEW

**Comment by glouw** [comment]
interesting, but Tinn was built for portability with chips like ARM and AVR in mind.

**Comment by tsandstr** [comment]
Sorry, I didn’t mean to submit a pull request. I just did this for a little fun in my own fork, you can disregard this request. I’m still getting the hang of using git.

**Comment by tsandstr** [comment]
Sorry, I didn’t mean to submit a pull request. I just did this for a little fun in my own fork, you can disregard this request. I’m still getting the hang of using git.

**Comment by glouw** [comment]
No problem. It looks good by the way. Your handle on modern C++ is good

**Comment by zoomx** [comment]
Arduino IDE uses C++ so it can be useful too, IMO.

**Comment by glouw** [comment]
True, but TINN can be compiled by all C++ compilers without any modification

**Pull request closed without merging**
